### ISSUE TITLE
Move project to paperless organization

### ISSUE THREAD

**Issue by ovv** [ovv/ansible-role-paperless#22]
See the-paperless-project/paperless#470

> But we should consider have the licences aligned. I noticed ansible-role-paperless is licensed unter the MIT License and paperless itself under the GNU General Public License v3.0.

**Comment by danielquinn** [comment]
I'm not sure I understand this ticket.  I'm reasonably sure that the MIT and GPL licenses are compatible (in that the GPL supercedes the MIT licensing in the case of distribution of the GPL product).  Even if I wanted to, given the number of contributors so far, I can't see any way of re-licensing Paperless under anything else (other than perhaps the AGPL or GPL4 should one ever be made).

So what's this ticket asking for exactly?

**Comment by ovv** [comment]
Hello @danielquinn, I think you might be confused between this repository (ovv/ansible-role-paperless) and the-paperless-project/paperless.

The aim of this ticket is to migrate ovv/ansible-role-paperless to the paperless organization.  IMO it's good to regroup related project to the organization for discoverability and maintenance.

As this repository and paperless don't have the same license (respectively MIT and GPL) it might be good to change this repository license to GPL to match paperless one (as I am the only contributor it should be doable).

**Comment by danielquinn** [comment]
Oh man, you're totally right.  Sorry, my bad.  I clicked a link from `the-paperless-project/paperless` and it never occurred to me that I'd left that project!
